name: Build and deploy Node.js app to Azure Web App - gitlabs

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'

      - name: Install dependencies
        run: npm ci

      - name: Build TypeScript
        run: ./node_modules/.bin/tsc

      - name: Zip artifact for deployment
        run: zip -r node-app.zip dist/ node_modules/ package.json prisma/ web.config

      - name: Upload artifact for deployment
        uses: actions/upload-artifact@v4
        with:
          name: node-app
          path: node-app.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: node-app

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_D029CC6A38264F11BC2401ADA112C00B }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_701B4EEFB17C43F2945E0B2AA87B7411 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_A8E4431A1BF348CCB6DE9A93D4F7CB27 }}

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'gitlabs'
          slot-name: 'Production'
          package: node-app.zip
